### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by OJFord** [paulirish/git-recent#13]
Nice tool! Only just found it. 😮 

I've submitted a PR at homebrew/homebrew-core#8979 to get it `brew install`able - this issue is in anticipation of being told the release needs to be `git tag`ged (or otherwise have the version number in it).

Might that be possible? 🙂

**Comment by paulirish** [comment]
sg! done: https://github.com/paulirish/git-recent/tags

**Comment by paulirish** [comment]
thanks man!

**Comment by OJFord** [comment]
Thanks! I've updated brew formula PR 🙂 .
