### ISSUE TITLE
git-recent's output does not highlight

### ISSUE THREAD

**Issue by Erichain** [paulirish/git-recent#15]
I don't know why, my iterm2 can't highlight the `git-recent`'s output.

**Comment by paulirish** [comment]
its probably the `--RAW-CONTROL-CHARS` arg that gets passed to `less`

the short version is "-R" or "-r" so that probably works?

**Comment by Erichain** [comment]
Sorry. I've tried to use `less` with `-R` or `-r` option, but it still didn't help.

**Comment by paulirish** [comment]
Interesting. Can you share a screenshot?

**Comment by Erichain** [comment]
![image](https://user-images.githubusercontent.com/10396124/32444081-ef2d974c-c2c6-11e7-9855-6d9829d23553.png)

Hi, this is the screenshot of my output. It's just all white.

In my another computer, the highlighting is right. I can't figure out what happened, there is no difference between the two configurations.

Thank you.

**Comment by Erichain** [comment]
Oh~ Sorry, I have found the reason. 

If I use Apple Git version (eg `Apple Git-81`), the highlight will be normal, but if I use the official Git version, the highlight will go away. 😄

So closing this issue.

**Comment by hezhizhen** [comment]
@Erichain I don't know the difference between Apple Git and official Git. Could you please explain it?

**Comment by ravicious** [comment]
@Erichain I have the same issue, but I use brew version of git (2.16.1).

**Comment by ravicious** [comment]
I can confirm that the highlight doesn't work on the newest version of git (2.16.1). I use the version supplied by homebrew.
